apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "balloon-api.fullname" . }}-upgrade
  labels:
    app.kubernetes.io/managed-by: {{.Release.Service | quote }}
    app.kubernetes.io/instance: {{.Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    helm.sh/chart: "{{.Chart.Name}}-{{.Chart.Version}}"
{{- if .Values.extraLabels }}
{{ toYaml .Values.extraLabels | indent 4 }}
{{- end }}
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: {{ include "balloon-api.fullname" . }}-upgrade
      labels:
        app.kubernetes.io/managed-by: {{.Release.Service | quote }}
        app.kubernetes.io/instance: {{.Release.Name | quote }}
        helm.sh/chart: "{{.Chart.Name}}-{{.Chart.Version}}"    
{{- if .Values.extraLabels }}
{{ toYaml .Values.extraLabels | indent 8 }}
{{- end }}
    spec:
      restartPolicy: Never
      initContainers:
      - name: wait-for-mongodb
        image: jwilder/dockerize
        command:
        - dockerize 
        - -timeout
        - 120s
        {{- if .Values.services.elasticsearch.uri }}
        {{- else }}
        - -wait
        - http://{{ .Release.Name }}-elasticsearch-client:9200
        {{- end }}
        {{- if .Values.mongodb.uri }}
        {{- else }}
        - -wait
        - tcp://{{ .Release.Name }}-mongodb-0.{{ .Release.Name }}-mongodb:27017
        {{- end }}
      containers:
      - name: balloon-api
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        command: 
        - ballooncli
        - upgrade
        - -vvvv
        {{- if .Values.upgrade.ignoreErrors }}
        - -i
        {{- end }}
        {{- if .Values.upgrade.forceApply }}
        - -f
        {{- end }}
        env:
        - name: BALLOON_CLAMAV_URI
        {{- if .Values.services.clamav.uri }}
          value: {{ .Values.services.clamav.uri }}
        {{- else }}
          value: tcp://{{ .Release.Name }}-clamav:3310
        {{- end }}
        - name: BALLOON_LIBREOFFICE_CONVERT_URL
        {{- if .Values.services.libreofficePreview.uri }}
          value: {{ .Values.services.libreofficePreview.uri }}
        {{- else }}
          value: http://{{ .Release.Name }}-lool-convert:9980
        {{- end }}
        - name: BALLOON_ELASTICSEARCH_URI
        {{- if .Values.services.elasticsearch.uri }}
          value: {{ .Values.services.elasticsearch.uri }}
        {{- else }}
          value: http://{{ .Release.Name }}-elasticsearch-client:9200
        {{- end }}
        - name: BALLOON_MONGODB_URI
        {{- if .Values.mongodb.uri }}
          value: {{ .Values.mongodb.uri }}
        {{- else }}
          value: mongodb://{{ .Release.Name }}-mongodb-0.{{ .Release.Name }}-mongodb:27017,{{ .Release.Name }}-mongodb-1.{{ .Release.Name }}-mongodb:27017,{{ .Release.Name }}-mongodb-2.{{ .Release.Name }}-mongodb:27017
        {{- end }}
        - name: BALLOON_URL
          value: {{ .Values.url }}
        - name: BALLOON_BURL_BROWSERLESS_URL
        {{- if .Values.services.burl.browserlessUri }}
          value: {{ .Values.services.burl.browserlessURI }}
        {{- else }}
          value: http://{{ .Release.Name }}-browserless-chrome:3000
        {{- end }}
{{- if .Values.extraVars }}
{{ toYaml .Values.extraVars | indent 8 }}
{{- end }}
        volumeMounts:
        - mountPath: /etc/balloon
          name: config-volume        
      volumes:
      - configMap:
          defaultMode: 420
          name: {{ .Release.Name }}-balloon-config
        name: config-volume        
  backoffLimit: 4
