{{- if and .Values.ingress.enabled (index .Values "balloon-web" "enabled") -}}
{{- $fullName := include "balloon.fullname" . -}}
{{- $releaseName := .Release.Name -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}-web
  labels:
    app.kubernetes.io/name: {{ include "balloon.name" . }}
    helm.sh/chart: {{ include "balloon.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  tls:
{{- range .Values.ingress.hosts }}
{{- if .tls }}
  - hosts:
    - {{ .name }}
    secretName: {{ .tls.secretName }}
{{- end }}
{{- end }}
  rules:
  {{- range .Values.ingress.hosts }}
    - host: {{ .name }}
      http:
        paths:
        - path: "/"
          pathType: Prefix
          backend:
            service:
              name: {{ $fullName }}-balloon-web
              port:
                name: http
  {{- end }}
{{- end }}
