{{- if .Values.ingress.enabled -}}
{{- $fullName := include "balloon.fullname" . -}}
{{- $releaseName := .Release.Name -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    app.kubernetes.io/name: {{ include "balloon.name" . }}
    helm.sh/chart: {{ include "balloon.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    nginx.ingress.kubernetes.io/affinity: cookie
    nginx.ingress.kubernetes.io/session-cookie-name: sticky-loolwsd
    nginx.ingress.kubernetes.io/session-cookie-path: /libreoffice
  {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  tls:
{{- range .Values.ingress.hosts }}
{{- if .tls }}
  - hosts:
    - {{ .name }}
    secretName: {{ .tls.secretName }}
{{- end }}
{{- end }}
  rules:
  {{- range .Values.ingress.hosts }}
    - host: {{ .name }}
      http:
        paths:
        {{- if index $.Values "balloon-web" "enabled" }}
        - path: "/"
          pathType: Prefix
          backend:
            service:
              name: {{ $fullName }}-balloob-web
              port:
                name: http
        {{- end }}
        {{- if index $.Values "balloon-proxy" "enabled" }}
        - path: "/api"
          pathType: Prefix
          backend:
            service:
              name: {{ $fullName }}-balloon-proxy
              port:
                name: http
        - path: "/openapi"
          pathType: Prefix
          backend:
            service:
              name: {{ $fullName }}-balloon-proxy
              port:
                name: http
        - path: "/share"
          pathType: Prefix
          backend:
            service:
              name: {{ $fullName }}-balloon-proxy
              port:
                name: http
        - path: "/wopi"
          pathType: Prefix
          backend:
            service:
              name: {{ $fullName }}-balloon-proxy
              port:
                name: http
        - path: "/webdav"
          pathType: Prefix
          backend:
            service:
              name: {{ $fullName }}-balloon-proxy
              port:
                name: http
        {{- end }}
        {{- if index $.Values "lool-collab" "enabled" }}
        - path: "/libreoffice"
          pathType: Prefix
          backend:
            service:
              name: {{ $fullName }}-lool-collab
              port:
                name: http
        {{- end }}
  {{- end }}
{{- end }}
