# Default values for balloon-jobs.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: gyselroth/balloon
  pullPolicy: IfNotPresent

hpa:
  enabled: false
  minReplicas: 1
  maxReplicas: 20
  metricType: Object
  metricName: balloon_processes_queued
  objectName: null
  resourceName: cpu
  averageUtilization: 50
  objectApiVersion: v1
  objectKind: Service
  averageValue: 10
  targetType: AverageValue

services:
  clamav:
    enabled: true
    uri: null
  elasticsearch:
    enabled: true
    uri: null
  libreofficeCollab:
    enabled: true
    uri: null
    wopiUri: null
  libreofficePreview:
    enabled: true
    uri: null
  burl:
    enabled: true
    browserlessUri: null

mongodb:
  uri: null

nameOverride: ""
fullnameOverride: ""

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: 100m
#    memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

extraLabels: {}

extraVars: {}

nodeSelector: {}

tolerations: []

affinity: {}
